# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    # mac:
    #   imageName: 'macOS-latest'
    # windows:
    #   imageName: 'windows-latest'

trigger:
- release

pool:
  vmImage: $(imageName)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    yarn install
  displayName: 'install'

- script: |
    yarn run build CURRENT_OS $(Agent.TempDirectory)
  displayName: 'build'

# - task: GitHubRelease@1
#   inputs:
#     gitHubConnection: 'github.com_rebelvg'
#     repositoryName: 'rebelvg/KolpaqueClientElectron'
#     action: edit
#     target: '$(Build.SourceVersion)'
#     tagSource: 'gitTag'
#     tagPattern: '.*'
#     releaseNotesSource: inline
#     assets: '$(Agent.TempDirectory)/KolpaqueClientElectron/*.zip'
#     addChangeLog: false

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Agent.TempDirectory)/KolpaqueClientElectron/KolpaqueClientElectron-linux-x64.zip'
    artifact: 'kolpaque_client_build'
    publishLocation: 'pipeline'
